### ISSUE TITLE
Answer missing from InteractionRequest in confirmation mode

### ISSUE THREAD

**Issue by dcaliste** [sailfishos/sailfish-secrets#109]
When an interaction request is set for confirmation, there is no way, IMHO, to get the user decision (cancel or agreed). The result of the action is successful, as it should be but the only thing that can be retireved is the userInput(). The same, cancellation action in a AlphaNumericInput request is not returned by the API.

I would suggest to add a isCancelled() getter in InteractionRequest class and similarly a isAccepted() one. In the case of a confirmation, userInput() would be empty, and in the case of AlphaNumericInput, isAccepted() would be true userInput() is valid and can be read.

**Comment by chriadam** [comment]
I believe that in the cancel case, an appropriate error code should be returned in the result - something like UserInteractionCanceledError or such.  We should check that we do indeed do that.

**Comment by dcaliste** [comment]
> I believe that in the cancel case, an appropriate error code should be returned in the result - something like UserInteractionCanceledError or such.

Welll, that's my point, I didn't find any error code with *cancel* or *interaction* related to canellation in the name.

From a coding point of view, it's simpler to add a new error code value, but IMHO, it's more meaningful to return successful and add a isCancelled() method, why:

* the operation indeed succeed in the sense there was no programmatic error or no network or whatever error. The user gives back its will as a cancellation.
* it's easier to discover when looking at the API, otherwise it should be mentioned in the documentation that in cancellation case the error code should be UserInteractionCancelledError.

**Comment by chriadam** [comment]
From the point of view of the operation, it is an error, since it could not be completed.  The reason is different from other causes of failure (that is, it's explicit user action as opposed to transient failure) but I think it is still better to report it the same way other errors are reported.

I've created https://github.com/sailfishos/sailfish-secrets/pull/112 for this one.  I guess we could add an "isCanceled()" method to UserInputRequest which returns true if the operation is complete and the error is InteractionViewUserCanceledError... what are your thoughts about that possibility?

**Comment by dcaliste** [comment]
Thank you for taking care of this in a PR. It's ok to keep it like that without an additional ```isCancelled()``` method.

**Comment by dcaliste** [comment]
Implemented by @chriadam in #112.
