### ISSUE TITLE
Proposition to make PluginInfo API reflect its read-only purpose

### ISSUE THREAD

**Issue by dcaliste** [sailfishos/sailfish-secrets#90]
The current API of {Crypto,Secret}/PluginInfo provides setters for read-only data such as plugin name or version. A grep in the code shows that ```setVersion()``` for instance is used in:

<pre>
./daemon/controller.cpp:        info.setVersion(plugin->version());
./lib/Crypto/serialization.cpp:    info.setVersion(version);
./lib/Secrets/serialization.cpp:    info.setVersion(version);
</pre>

which are purely internal methods. Maybe it could be clearer to remove these setters and pass these values at construct time.

Additional side note about PluginInfo API: I guess it will be used in UI to display selectors for crypto plugin to use when performing a signature action for instance. In that case, is it not too restrictive to make it a Q_GADGET? The available property is clearly something that may change and should notify on change. I know that plugins currently don't have the possibility to notify the main thread of changes in general, but they will eventually have and will it be too late to change from Q_GADGET to Q_OBJECT, or not?

**Comment by chriadam** [comment]
I agree that we should make those construct only, rather than writable, and the setters should be removed.

On the second question: we currently don't offer any signals from the daemon (keys changed, collections changed, plugin info changed, etc) and thus all information retrieved from the daemon is considered "inert" data.  In the future, we should provide such signals, however when we do so I think it would be better to keep the data objects inert (i.e. Q_GADGET) and instead allow the client to simply and easily get the new / updated information, via the signal parameters (e.g. perhaps allowing signal filtering or similar).

**Comment by dcaliste** [comment]
I will see if I have time to propose a PR next week.

Ok for future plan to signal to the clients via the manager or something else and keep these data passing structure stupid simple.
